# version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"




# SQLiteを使用する場合、MySQLサービスは不要です。以上のように設定を簡略化できます。

# 以下は通常の作成しました









# version: '3.8'

# services:
#   app:
#     image: php:8.2-fpm
#     container_name: laravel_app
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mysql
#     command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"

#   mysql:
#     image: mysql:8.0
#     container_name: laravel_mysql
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

